# fly.toml app configuration file generated for backend-bold-smoke-6218 on 2025-11-13T11:25:24-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-bold-smoke-6218'
primary_region = 'iad'

[build]

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/health"

  [[services.tcp_checks]]
    restart_limit = 0

[deploy]
  release_command = "bun run src/db/migrate.ts"

[[mounts]]
  source = "sportsgpt_data"
  destination = "/data"
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
